// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igkqepaexhyjnyiuoqrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlna3FlcGFleGh5am55aXVvcXJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyMzMwNDYsImV4cCI6MjA1MzgwOTA0Nn0.x5DDGKmAO5fxFa1Bf9-IzvLWBryjyYDlne9eQ3QYTa0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);